### ISSUE TITLE
Fibaro shutter not recognized by home assistant

### ISSUE THREAD

**Issue by Vortjong** [harriedegroot/nl.hdg.mqtt#30] opened 2020-01-03 09:09 UTC
I'm using mqtt hub together with home assistant discovery. 
Somehow the fibaro shutter information is not usable by home assistant (logging from home assistant):

Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'name': 'Keuken - Rolluik', 'unique_id': 'e91b3a34-60c9-41b6-9b56-3fc81afe1c76_cover', 'value_template': '{{ value }}', 'position_topic': 'homie/homey-570b78789aac671e67acccb6/keuken---rolluik/dim', 'position_closed': 0, 'position_open': 1, 'position_command_topic': 'homie/homey-570b78789aac671e67acccb6/keuken---rolluik/dim/set', 'set_position_template': '{{ value }}', 'device': {'identifiers': 'homey-570b78789aac671e67acccb6_e91b3a34-60c9-41b6-9b56-3fc81afe1c76', 'name': 'Keuken - Rolluik'}, 'platform': 'mqtt'},)

The measure-power and meter-power are parsed correctly and appear in home assistant

**Comment by Patriciawa** [comment] 2020-07-07 09:19
@Vortjong did you find a fix for the fibaro shutter ?

**Comment by Vortjong** [comment] 2020-08-25 11:07
No, bypassing it by using a virtual device is also not the best solution. I have not the idea this is maintained. I'm looking into the code to see whether I can fix it,

**Comment by harriedegroot** [comment] 2020-08-25 17:00
@Vortjong Did you find the root cause of the issue? Of course I'm here to help. FYI: I don't use Homey anymore, therefore it's a little harder debugging :). I will 'maintain' this library where I can, but adding new features is left for the community. All pull-request will be reviewed and I'll update the app if needed.

**Comment by Vortjong** [comment] 2020-08-25 17:18
First of all, thanks for the app, it enables me to combine homey with home assistant !

I dived into it a little bit and I think the issue is not even in the hub. 
The problem is with a fibaroshutter. When added to homey, it will get a DIM level.
When this is published on MQTT it has the following properties (type is windowcoverings):
* dim
* measure-power
* meter-power
When home-assitant is parsing the JSON, it will parse measure-power and meter-power but it will fail on dim.
According to the MQTT cover documentation of home-assitant, it does support positions but this should be called "position" i.s.o dim.

I now **assume** the hub just takes the values from the fibaro device, which is using dim, so the problem is probably not for the hub.

I'm not an expert on this type of code, so I do not know whether my assumption is correct.
Would it be possible to modify the properties when the hub creates the message.
I can test when needed on my homey.

I'm also looking into the code of HA.

This is error from HA
'value_template': '{{ value }}', 'position_topic': 'homie/homey-570b78789aac671e67acccb6/keuken---rolluik/dim', 'position_closed': 0, 'position_open': 1, 'position_command_topic': 'homie/homey-570b78789aac671e67acccb6/keuken---rolluik/dim/set', 'set_position_template': '{{ value }}', 'device': {'identifiers': 'homey-570b78789aac671e67acccb6_e91b3a34-60c9-41b6-9b56-3fc81afe1c76', 'name': 'Keuken - Rolluik'}, 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 183, in async_discover config = PLATFORM_SCHEMA(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 208, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 287, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 283, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: extra keys not allowed @ data['position_command_topic']

**Comment by harriedegroot** [comment] 2021-03-28 11:57
Fixed set position topic, see commit: https://github.com/harriedegroot/nl.hdg.mqtt/commit/c26e966602d43351536d14fe466d5f8aa158f78b

Issue should be resolved with v3.0.2 of the hub.

**Closed** 2021-03-28 11:57 UTC
